#!/bin/bash
set -e

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

{
    cat <<-'EOH'
# This file contains a list of contributors to this project.
# It is generated by the 'generate-authors.sh'.
EOH
echo
git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > AUTHORS
